version: '3.9'

services:

  authorization-microservice:
    container_name: authorization-microservice
    image: authorization-microservice
    build:
      context: ./AuthorizationMicroService
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    expose:
      - "5000"
    environment: 
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - database
      
  store-microservice:
    container_name: store-microservice
    image: store-microservice
    build:
      context: ./StoreMicroService
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    expose:
      - "5001"
    environment: 
      ASPNETCORE_URLS: http://+:5001
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - authorization-microservice
      - database
      
  production-microservice:
    container_name: production-microservice
    image: production-microservice
    build:
      context: ./ProductionMicroService
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    expose:
      - "5002"
    environment: 
      ASPNETCORE_URLS: http://+:5002
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - authorization-microservice
      - store-microservice
      - employee-microservice
      - database
      
  order-microservice:
    container_name: order-microservice
    image: order-microservice
    build:
      context: ./OrderMicroservice
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    expose:
      - "5003"
    environment: 
      ASPNETCORE_URLS: http://+:5003
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - authorization-microservice
      - store-microservice
      - employee-microservice
      - database
      
  employee-microservice:
    container_name: employee-microservice
    image: employee-microservice
    build:
      context: ./EmployeeMicroservice
      dockerfile: Dockerfile
    ports:
      - 5004:5004
    expose:
      - "5004"
    environment: 
      ASPNETCORE_URLS: http://+:5004
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - authorization-microservice
      - database

  nginx: 
    container_name: nginx
    image: nginx
    depends_on: 
      - authorization-microservice
      - store-microservice
      - employee-microservice
      - production-microservice
      - order-microservice
    ports: 
      - "8080:8080"
    build:
      context: ./nginx

  database:
    container_name: database
    image: database
    ports:
      - 1433:1433
    expose:
      - "1433"  
    build: 
      context: ./DB
      dockerfile: Dockerfile
